---
title: "PSTAT 5A: Understanding Data"
subtitle: "Schedule of Topics"
author:
  - name: "Ethan Marzban"
    affiliations:
      - name: "Summer Session A, 2023"
author-title: "Instructor"
affiliation-title: "Quarter"
format: html
css: "../schedule.css"
---

::: callout-caution
## Disclaimer

This schedule is tentative, and is subject to change. Please check back regularly for updates!
:::

Last Updated: *Monday, July 3, 2023*\

**As a reminder:** Monday sections are Lab Sections and Wednesday sections are Discussion Sections.

\

+---------------+---------------------------------------------------------------------------------------------------------------------------------+-----------------------------------------------------------------------------------------------------------------+------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Week          | Lectures                                                                                                                        | Discussion Worksheet                                                                                            | Lab                                                                                                                                                        |
+===============+=================================================================================================================================+=================================================================================================================+============================================================================================================================================================+
| **1**         | -   <a href = "Lectures/Lecture00/Lec00.qmd" class = "button label-outline" target = "_blank">00: Introduction</a>              | Worksheet <a href = "../Files/Wkshts/Wksht01_Blank.pdf" class = "button label-outline" target = "_blank">01</a> | <a href = "Labs/Lab01/lab01.qmd" class = "button label-outline" target = "_blank">Lab 01</a> <br /> Introduction to Python                                 |
|               |                                                                                                                                 |                                                                                                                 |                                                                                                                                                            |
| (6/26 - 7/02) | -   <a href = "Lectures/Lecture01/Lec01.qmd" class = "button label-outline" target = "_blank">01: Descriptive Statistics I</a>  | <a href = "../Files/Wkshts/Wksht01_Solns.pdf" class = "button label-outline" target = "_blank">Solns</a>        | <a href = "../Files/Labs/Lab01_Solns.pdf" class = "button label-outline" target = "_blank">Solns</a>                                                       |
|               |                                                                                                                                 |                                                                                                                 |                                                                                                                                                            |
|               | -   <a href = "Lectures/Lecture02/Lec02.qmd" class = "button label-outline" target = "_blank">02: Descriptive Statistics II</a> |                                                                                                                 |                                                                                                                                                            |
|               |                                                                                                                                 |                                                                                                                 |                                                                                                                                                            |
|               |     -   Remember to read the section titled "Transforming Data" on your own                                                     |                                                                                                                 |                                                                                                                                                            |
|               |                                                                                                                                 |                                                                                                                 |                                                                                                                                                            |
|               | -   <a href = "Lectures/Lecture03/Lec03.qmd" class = "button label-outline" target = "_blank">03: Intro to Probability</a>      |                                                                                                                 |                                                                                                                                                            |
|               |                                                                                                                                 |                                                                                                                 |                                                                                                                                                            |
|               | -   <a href = "Lectures/Lecture04/Lec04.qmd" class = "button label-outline" target = "_blank">04: Counting</a>                  |                                                                                                                 |                                                                                                                                                            |
|               |                                                                                                                                 |                                                                                                                 |                                                                                                                                                            |
|               | -   <a href = "../Files/QzSolns/Qz01_solns.pdf" class = "button label-outline" target = "_blank">Qz01 Solns</a>                 |                                                                                                                 |                                                                                                                                                            |
+---------------+---------------------------------------------------------------------------------------------------------------------------------+-----------------------------------------------------------------------------------------------------------------+------------------------------------------------------------------------------------------------------------------------------------------------------------+
| **2**         | -   <a href = "Lectures/Lecture05/Lec05.qmd" class = "button label-outline" target = "_blank">05: Conditional Probabilities</a> | Worksheet 02                                                                                                    | <a href = "Labs/Lab02/lab02.qmd" class = "button label-outline" target = "_blank">Lab 02</a> <br /> Data Classes, Comparisons, Conditionals, and Functions |
|               |                                                                                                                                 |                                                                                                                 |                                                                                                                                                            |
| (7/03 - 7/09) | -   06: **NO LECTURE** (Fourth of July)                                                                                         |                                                                                                                 |                                                                                                                                                            |
|               |                                                                                                                                 |                                                                                                                 |                                                                                                                                                            |
|               | -   07: Review                                                                                                                  |                                                                                                                 |                                                                                                                                                            |
|               |                                                                                                                                 |                                                                                                                 |                                                                                                                                                            |
|               | -   08: **Midterm 1**                                                                                                           |                                                                                                                 |                                                                                                                                                            |
+---------------+---------------------------------------------------------------------------------------------------------------------------------+-----------------------------------------------------------------------------------------------------------------+------------------------------------------------------------------------------------------------------------------------------------------------------------+
| **3**         | -   09: Discrete Random Variables                                                                                               | Worksheet 04                                                                                                    | Lab03: Descriptive Statistics, Sampling Distributions, and Simulations                                                                                     |
|               |                                                                                                                                 |                                                                                                                 |                                                                                                                                                            |
| (7/10 - 7/16) | -   10: Continuous Random Variables                                                                                             |                                                                                                                 |                                                                                                                                                            |
|               |                                                                                                                                 |                                                                                                                 |                                                                                                                                                            |
|               | -   11: Introduction to Inference                                                                                               |                                                                                                                 |                                                                                                                                                            |
|               |                                                                                                                                 |                                                                                                                 |                                                                                                                                                            |
|               | -   12: Confidence Intervals for Proportions                                                                                    |                                                                                                                 |                                                                                                                                                            |
+---------------+---------------------------------------------------------------------------------------------------------------------------------+-----------------------------------------------------------------------------------------------------------------+------------------------------------------------------------------------------------------------------------------------------------------------------------+
| **4**         | -   13: Confidence Intervals for Means                                                                                          | Worksheet 05                                                                                                    | Lab04: Percentiles, QQ-Plots, and Loops                                                                                                                    |
|               |                                                                                                                                 |                                                                                                                 |                                                                                                                                                            |
| (7/17 - 7/23) | -   14: Hypothesis Testing for Proportions                                                                                      |                                                                                                                 |                                                                                                                                                            |
|               |                                                                                                                                 |                                                                                                                 |                                                                                                                                                            |
|               | -   15: Review                                                                                                                  |                                                                                                                 |                                                                                                                                                            |
|               |                                                                                                                                 |                                                                                                                 |                                                                                                                                                            |
|               | -   16: **Midterm 2**                                                                                                           |                                                                                                                 |                                                                                                                                                            |
+---------------+---------------------------------------------------------------------------------------------------------------------------------+-----------------------------------------------------------------------------------------------------------------+------------------------------------------------------------------------------------------------------------------------------------------------------------+
| **5**         | -   17: Hypothesis Testing for Means                                                                                            | Worksheet 06                                                                                                    | Lab05: Markdown Syntax, and Importing Data                                                                                                                 |
|               |                                                                                                                                 |                                                                                                                 |                                                                                                                                                            |
| (7/24 - 7/30) | -   18: Two-Sample *t*-Tests                                                                                                    |                                                                                                                 |                                                                                                                                                            |
|               |                                                                                                                                 |                                                                                                                 |                                                                                                                                                            |
|               | -   19: ANOVA (Analysis of Variance)                                                                                            |                                                                                                                 |                                                                                                                                                            |
|               |                                                                                                                                 |                                                                                                                 |                                                                                                                                                            |
|               | -   20: Correlation, and an Intro to Statistical Modeling                                                                       |                                                                                                                 |                                                                                                                                                            |
+---------------+---------------------------------------------------------------------------------------------------------------------------------+-----------------------------------------------------------------------------------------------------------------+------------------------------------------------------------------------------------------------------------------------------------------------------------+
| **6**         | -   21: Regression                                                                                                              |                                                                                                                 | Lab06: Exploratory Data Analysis                                                                                                                           |
|               |                                                                                                                                 |                                                                                                                 |                                                                                                                                                            |
| (7/31 - 8/06) | -   22: Regression Diagnostics                                                                                                  |                                                                                                                 |                                                                                                                                                            |
|               |                                                                                                                                 |                                                                                                                 |                                                                                                                                                            |
|               | -   23: Sampling Techniques and Experimental Design                                                                             |                                                                                                                 |                                                                                                                                                            |
|               |                                                                                                                                 |                                                                                                                 |                                                                                                                                                            |
|               | -   24: Review                                                                                                                  |                                                                                                                 |                                                                                                                                                            |
|               |                                                                                                                                 |                                                                                                                 |                                                                                                                                                            |
|               | -   **FINAL EXAM: Friday, August 4 from 4 - 7pm**                                                                               |                                                                                                                 |                                                                                                                                                            |
+---------------+---------------------------------------------------------------------------------------------------------------------------------+-----------------------------------------------------------------------------------------------------------------+------------------------------------------------------------------------------------------------------------------------------------------------------------+
