---
title: "PSTAT 5A: Understanding Data"
subtitle: "Course Syllabus"
author:
  - name: "Annie Adams"
    affiliations:
      - name: "Summer Session B, 2025"
author-title: "Instructor"
affiliation-title: "Quarter"
format: html
linkcolor: "#ffa07a"
---

**WELCOME TO PSTAT 5A**! I am very excited to introduce to you the wonderful fields of Statistics and Data Science. As our world becomes ever more saturated with data, the need for data literacy becomes increasingly important. By the end of this course, I hope you will be able to think critically about statistical studies and results, understand how data can be used to simultaneously inform and manipulate, and begin applying your new skills to your future endeavors. I am very much looking forward to a great quarter with all of you!

--- Annie

## Lecture Information

::: callout-note
## **Lecture Times and Locations**

M, T, W, Th: 9:30 am - 10:50 am in **HSSB 1173**
:::

## Course Staff

\vspace{-5mm}

::: {layout-ncol="2"}
+-----------------+----------------------------------------------------------------------------------------------------------------------------------------------+
| **Instructor:** | Annie Adams
+:================+:=============================================================================================================================================+
| **Email:**      | [aradams@ucsb.edu](mailto:aradams@ucsb.edu)  
+-----------------+----------------------------------------------------------------------------------------------------------------------------------------------+
| **Help Hours:** | -   [**Mondays:**]{.underline} 11:00 am - 12:00 pm 
|                 | -   [**Wednesdays:**]{.underline} 11:00 am - 12:00 pm 
+-----------------+----------------------------------------------------------------------------------------------------------------------------------------------+

: {tbl-colwidths="\[20, 30\]"}

+------------------------------------------------+
| **TAs**                                        |
+------------------------------------------------+
| **Daniel Silva**\                             
| ([dcsilva\@ucsb.edu](mailto:dcsilva@ucsb.edu)) 
+------------------------------------------------+
| **Hezhong Zhang**\                            
| ([hzhang586\@umail.ucsb.edu](mailto:hzhang586@umail.ucsb.edu)) |
+------------------------------------------------+

: {tbl-colwidths="\[50\]"}
:::


## Schedule of Sections

|       Times       |       TA       |  Location   |
|:-----------------:|:--------------:|:-----------:|
| TR 11:00 - 11:50pm |  | PHELPS 1513 |
| TR 12:00 - 12:50pm |  | PHELPS 1525 |
| TR 1:00 - 1:50pm |  | PHELPS 1525 |

## Course Description

The official description of this course, from the Course Catalog, is:

> Introduction to data science. Concepts of statistical thinking. Topics include random variables, sampling distributions, hypothesis testing, correlation and regression. Visualizing, analyzing and interpreting real world data using Python. Computing labs required.

## Textbook(s)

This quarter, we do not have a required textbook- the lecture slides and lab activities are designed to be self-sufficient. However, the following textbooks are highly recommended:

-   *OpenIntro: Statistics*. David Diez, Mine Çetinkaya-Rundel, and Christopher D Barr. (free version, courtesy of the authors, available at <a href = "https://leanpub.com/os/" target = "_blank">https://leanpub.com/os</a>)

-   *Computational and Inferential Thinking: The Foundations of Data Science*. Ani Adhikari and John DeNero. (available at: <a href = "https://inferentialthinking.com/" target = "_blank">https://www.inferentialthinking.com</a>)

-   *StatClass* (2nd Edition, Revised). Dawn E. Holmes and Lubella A. Lenaburg

## Course Components

The following are the assignments and metrics that will be used to compute your final grade in this course:

### Labs

Every Tuesday you will work through a Lab assignment. It is advised that you turn in the Lab at the end of the section on Tuesdays, but you will have until the end of Thursday (11:59p) to submit your work through Gradescope. Your TA will explain more about the structure of lab during your first Section meeting of the quarter.

### Quizzes

Quizzes will be administered **asynchronously** on **Mondays**, through **Gradescope**. Specifically, the quiz will remain open from 8am until 11:59pm, and you must find **60 consecutive minutes** to take the quiz. (Consecutive means you cannot start the quiz, and then come back to it later- once you start, you will have 60 minutes to both complete the quiz as well as upload your work). I encourage you to spend **45 minutes working on the quiz, and 15 minutes uploading**. No quiz scores will be dropped. There is no quizzes on the first and last week of class.

### Exam

There is a **final** exam for this class. You are required to take the final exam, which will take place during the last lecture.


### Homework:

There will be weekly homework due on Thursday at 11:59p. It must be turned into Gradescope. No late homework will be accepted since solutions to the homework will be posted at midnight (Thursday to Friday). I advise you review your homework in preparation for the quiz on Monday.

### Schedule of Due Dates

**Lab1**: Thursday, August 7 at 11:59pm
**HW1**: Thursday, August 7 at 11:59pm
**Quiz1**: Monday, August 11 (8a- 11:59p)

**Lab2**: Thursday, August 14 at 11:59pm
**HW2**: Thursday, August 14 at 11:59pm
**Quiz2**: Monday, August 18 (8a- 11:59p)

**Lab3**: Thursday, August 21 at 11:59pm
**HW3**: Thursday, August 21 at 11:59pm
**Quiz3**: Monday, August 25 (8a- 11:59p)

**Lab4**: Thursday, August 28 at 11:59pm
**HW4**: Thursday, August 28 at 11:59pm
**Quiz4**: Monday, Sept 1 (8a- 11:59p)

**Lab5**: Thursday, Sept 4 at 11:59pm
**HW5**: Thursday, Sept 4 at 11:59pm
**Quiz5**: Monday, Sept 8 (8a- 11:59p)

**Lab6**: Thursday, Sept 11 at 11:59pm
**HW6**: Thursday, Sept 11 at 11:59pm 

## Grading Scheme

Your final grade will be computed using the following weights:

|                    |     |
|:-------------------|:----|
| Homework:          | 25% |
| Labs:              | 25% |
| Quizzes:           | 25% |
| Final Examination: | 25% |


Please note that late submissions for any of the above will **not** be accepted. Additionally, make-up exams cannot be accommodated.

Your final letter grade will be issued according to the following scheme (cutoffs between plusses and minuses will be calculated at the end of the quarter):

-   A^--^ -- A^+^: 90 -- 100%
-   B^--^ -- B^+^: 80 -- 89.99%
-   C^--^ -- C^+^: 70 -- 79.99%
-   D^--^ -- D^+^ : 60 -- 69.99%
-   F: 0 -- 59.99%

I have elected to adopt an uncurved grading scheme to eliminate any sense of "competition" among students; I highly encourage you all to collaborate with and uplift each other. Having said that, I will certainly consider adjusting the cutoffs (naturally, in everyone's favor) at the end of the quarter if necessary.

## Academic Integrity

As a member of the UCSB community, it is expected that you will act with academic integrity. This means, among other things, that the work you submit should be entirely your own and not copied from any external sources. Collaboration on non-quiz and non-exam assignments is perfectly acceptable (and even encouraged), but the work you submit should still be your own; you can't have someone else write up solutions for you.

Anyone found guilty of academic misconduct will be reported to the Academic Senate, and will receive at minimum a failing grade on the assignment in question; further actions may also include failing the course, and marks being made on permanent records. Depending on the severity of the infraction, expulsion is also a possibility.

Basically, don't cheat- please! If you're ever struggling with course material, please come talk to me or the TA's. We are truly here for you, and want only the best for you.

<!-- ### ChatGPT -->

<!-- It is perhaps evident that the recent rise of Artificial Intelligence-driven chatbots has somewhat shifted the general paradigm of education. Though these resources pose obvious concerns with regards to Academic Integrity, their merit as a useful tool for learning cannot be overlooked. As such, I have adopted the following policy with regards to the use of ChatGPT (and its equivalents) in this course: its use is permitted on homework and labs, **so long as you clearly indicate, somewhere on the work you turn in, that you have utilized it**. It is, however, **strictly forbidden** to use ChatGPT (or any of its equivalents) on quizzes and exams; students found to be in violation of this risk academic sanctions in line with the section on Academic Integrity above. -->

<!-- ## Intellectual Property -->

<!-- You've probably seen a clause on other syllabi stating something to the effect of "all material in this course is the intellectual property of myself and may not be shared with anyone outside this class without my explicit written permission." -->

<!-- Though this does still hold true for this course, I will be making most course-related material available on a public GitHub site, which can be accessed here: <a href = "https://pstat5a.github.io" target = "_blank">https://pstat5a.github.io</a>. -->

## Disabled Students Program (DSP)

If you have a disability, or otherwise require accommodations for the exams and/or quizzes please reach out to the Disabled Students Program (DSP) ASAP to ensure your request(s) for accommodation can be processed. We ask that all requests be logged **at least a week in advance**, to ensure the system enough time to process. Please note that we cannot grant any requests for accommodations unless they come to us from DSP directly.

## Technology Needs

As a part of this course, you will be required to program in Python. Though the Lab Sections take place in specially designed classrooms that come equipped with computers, your homework and quizzes may cover Python-related questions, which means we expect you to have access to a laptop capable of connecting to the internet. If you do not currently possess such a laptop, please check out UCSB's Basic Needs Resource [page on Technology Resources](https://food.ucsb.edu/resources/technology-resources) to try and acquire one.

## Section Switching

As mentioned above, Sections (both Discussion and Lab) take place in special "Collaborate Classrooms" which are equipped with laptops. There are a fixed number of seats and laptops in these classrooms, meaning we cannot under any circumstance over-enroll sections. Therefore, if you want to switch section unofficially (we do not have the ability to switch your official enrollment through GOLD), please follow the steps at <a href="https://docs.google.com/spreadsheets/d/1sD886stfYTJrYvQ7ufpauKpvXUsy_3cIBRcAhYeWILY/edit?gid=0#gid=0" target = "_blank">this</a> link. Any requests to switch sections that do not adhere to the guidelines posted at that link will be ignored.

## Email Policy

I will try my best to answer all emails within 48 hours. If you have not gotten a response from me in that time frame, please send me a followup as I probably missed it. Please refrain from asking coding or conceptual questions over email, this is better to be answered in person during instructor or TA office hours. 

<!-- This quarter, I am adopting a **no-email policy**. If you have any questions or concerns, please come to my office hours to express them; if you are unable to make either of my office hours, please see me after class to set up a meeting time. Please note that I will ignore any emails sent to my inbox. Thank you! -->

<!-- If you need to send an email to me (Ethan), please include "PSTAT 5A" in the subject line of your email. Additionally, please allow up to one business day for a reply (though I will do my best to get back to you ASAP). -->

<!-- Please note that I do not answer questions with extensive mathematics/equations over email (as trying to communicate in math over email can be a bit of a technical nightmare) Instead, if you have questions relating to course content I welcome you to either ask over <a href = "https://discord.gg/9wmDgXXajQ" target = "_blank">Discord</a> or during one of my Office Hours. -->

<!-- Also, should you need to include your TA, please send a **single** email to both your TA and myself, as opposed to separate emails to the two of us. Thank you! -->

## Disclaimer

This syllabus and much of the content for this course has been graciously borrowed from the original work of Ethan P. Marzban with some modifications. Thank you, Ethan!